### PR TITLE
Volume II proofread

### PR DESCRIPTION
**Pull request by jpnance**
In this pull request are many, many bits of proofreading, largely surrounding Chapters 42 through 79 and the three Appendices but occasionally being carried back into Chapters 1 through 41 as well. I did my best to make no editorial decisions (I'll open those up as issues later) and focus exclusively on the 1913 scans that were available to me. I'm nearly certain I missed a bunch of things (for instance, I just didn't have the energy to go back and include Oxford commas everywhere in the text, as the 1913 edition does) but I think I've very significantly improved the quality of the SE version of "Roughing It" with these updates.

I hope y'all will agree but, of course, please let me know if we need to remove or modify any of these commits.

### CODE REVIEW

**Comment by acabal** [comment]
The fixes I made based on the other issues you opened have introduced merge conflicts. Can you fix those and force push to this PR before I take a look at this?

Did you make these changes based on the page scans in the ebook's metadata, or some other page scans?

**Comment by jpnance** [comment]
Sure, I'll try to get an updated PR over later today. All of the changes were made based on the page scans currently referenced in the metadata, yes, though this was recently (a few weeks ago) updated to a different set of scans than the ebook launched with.

**Comment by jpnance** [comment]
I believe this is ready for review now. A heads up that there are a few issues that I'm not sure what to do with when I run `se lint .`.

**Comment by acabal** [comment]
Github says this can't be rebased due to conflicts. Can you take a look?

We don't do merge commits, we generally rebase onto master instead.

**Comment by jpnance** [comment]
I think this can be fast-forwarded now? Manual rebasing is always an adventure.

**Comment by acabal** [comment]
OK, looks like it should work now. I'm leaving for the day but hopefully I can review this tomorrow. Thanks!

**Comment by acabal** [comment]
OK, everything looks good! This must be the biggest PR I've ever accepted. Great work!

You should consider producing a new ebook for SE. You have a really good eye for detail and that goes a long way towards making an excellent ebook. [Check out our contributors page](https://standardebooks.org/contribute#technical-contributors) if you want to give it a shot!

**Pull request merged**
